#!/usr/bin/env bash

set -e

DOTFILES="$HOME/i3-dotfiles-fedora"
TMP="$(mktemp -d)"

trap 'rm -rf "$TMP"' EXIT

[ ! -d "$DOTFILES" ] && { echo "❌ $DOTFILES not found. Clone the repo to $HOME first."; exit 1; }

cd "$DOTFILES"

echo "📦 Adding rpmfusion..."
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf update

echo "📦 Installing repo packages..."
grep -vE '^\s*(#|$)' pkg.list | xargs sudo dnf -y install --allowerasing --skip-unavailable

echo "⚙️ Running post-install scripts..."
for script in post-install-scripts/*; do
    [ -x "$script" ] && "$script" || echo -e "\e[33m⚠ Script failed: $script\e[0m"
done

clear && echo "📁 Installing dotfiles..."
while read -r rel; do
    [ -z "$rel" ] && continue

    src="$DOTFILES/$rel"
    dst="$HOME/$rel"

    if [ ! -e "$src" ]; then
        echo -e "\e[31m✖ Missing in repo: $rel\e[0m"
        continue
    fi

    if [ -e "$dst" ]; then
        echo -e "\e[33m⚠ Replacing $dst\e[0m"
        rm -rf "$dst"
    fi

    mkdir -p "$(dirname "$dst")"
    cp -a "$src" "$dst"

    echo -e "\e[32m✔ Installed $rel\e[0m"
done < "$DOTFILES/dotfile-paths"


echo -e "\n\n📦 Installing Starship, AppImage Integrator, Lazy Weather, Lazy Snapper, Brave, VS Code, Viber, and AnyDesk...\n"
curl -sS https://starship.rs/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/apapamarkou/appimage-integrator/main/install | bash
curl -sSL https://raw.githubusercontent.com/apapamarkou/lazy-weather/main/install | bash
curl -sSL https://raw.githubusercontent.com/apapamarkou/lazy-snapper/main/install | bash
curl -fsSL https://raw.githubusercontent.com/apapamarkou/lazy-package/main/install | bash
curl -sSL https://raw.githubusercontent.com/apapamarkou/linxpad/main/install | bash

curl -fsS https://dl.brave.com/install.sh | sh
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc && echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
sudo dnf update
sudo dnf install -y code
sudo dnf install -y https://download.cdn.viber.com/desktop/Linux/viber.rpm
sudo tee /etc/yum.repos.d/AnyDesk-Fedora.repo << "EOF" 
[anydesk]
name=AnyDesk Fedora - stable
baseurl=http://rpm.anydesk.com/fedora/$basearch/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://keys.anydesk.com/repos/RPM-GPG-KEY
EOF
sudo dnf install -y anydesk

pip install pulsemixer

curl -L -o /tmp/JetBrainsMono.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip && mkdir -p ~/.local/share/fonts && unzip -o /tmp/JetBrainsMono.zip -d ~/.local/share/fonts && rm /tmp/JetBrainsMono.zip


echo "✅ Done!"
echo "the system is going to reboot in 5 seconds."
echo "press Control+C to abort"
sleep 5
reboot

