#!/bin/bash

# __   __    _   _ _   _ ___  __
# \ \ / /__ | | | | \ | (_) \/ /
#  \ V / _ \| | | |  \| | |\  / 
#   | | (_) | |_| | |\  | |/  \ 
#   |_|\___/ \___/|_| \_|_/_/\_\
#
# Lisence GPL3
# Homepage: https://github.com/apapamarkou/younix
# Author: Andrianos Papamarkou
# Email: papamarkoua@gmail.com

sudo dnf install -y fzf
clear

echo "Locale Selector"
echo "----------------"
echo
echo "This script will help you select and configure your locale."
echo "Your current locale is: $(locale | grep LC_CTYPE= | cut -d'=' -f2)"
echo

read -p "Do you want to change it? (Y/n) " -n 1 -r
echo

if [[ $REPLY =~ ^[Nn]$ ]]; then
    exit 1
fi

# List available locales on Fedora
selected_locale=$(localectl list-locales | fzf --prompt="Select locale: " --height=100% --layout=reverse)

if [ -z "$selected_locale" ]; then
    echo "No locale selected. Exiting."
    exit 1
fi

# Install the corresponding glibc langpack
lang_code=$(echo "$selected_locale" | cut -d'_' -f1)
sudo dnf install -y "glibc-langpack-${lang_code}"

PROFILE="$HOME/.profile"
MARKER_START="# locale-config-start"
MARKER_END="# locale-config-end"

# Remove existing locale block if present
if grep -q "$MARKER_START" "$PROFILE" 2>/dev/null; then
    sed -i "/$MARKER_START/,/$MARKER_END/d" "$PROFILE"
fi

cat >> "$PROFILE" << EOF
$MARKER_START
export LANG=en_US.UTF-8
export LC_CTYPE="$selected_locale"
export LC_NUMERIC="$selected_locale"
export LC_TIME="$selected_locale"
export LC_COLLATE=C
export LC_MONETARY="$selected_locale"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="$selected_locale"
export LC_NAME="$selected_locale"
export LC_ADDRESS="$selected_locale"
export LC_TELEPHONE="$selected_locale"
export LC_MEASUREMENT="$selected_locale"
export LC_IDENTIFICATION="$selected_locale"
export LC_ALL=
$MARKER_END
EOF

echo "~/.profile updated with locale: $selected_locale"
sleep 2
