#!/usr/bin/env bash

# Lisence GPL3
# Author: Andrianos Papamarkou
# Email: papamarkoua@gmail.com

clear

echo "Creating update-grub script..."
echo "--------------------------------"
echo
echo "This script will create a debian-like script named 'update-grub' in the /usr/sbin directory for easy update the grub boot loader."
echo

read -p "Do you want this feat? (Y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]; then
    exit 1
fi

# Detect grub.cfg path (EFI or BIOS)
if [ -d /sys/firmware/efi ]; then
    grub_cfg="/boot/efi/EFI/fedora/grub.cfg"
else
    grub_cfg="/boot/grub2/grub.cfg"
fi

target_file="/usr/sbin/update-grub"

sudo tee "$target_file" > /dev/null << EOF
#!/bin/sh
set -e
exec grub2-mkconfig -o $grub_cfg "\$@"
EOF

sudo chown root:root "$target_file"
sudo chmod 755 "$target_file"

echo "$target_file created and made executable."
sleep 2
