#!/usr/bin/env bash

clear
# Ask if they want to install Lazy Weather
read -p "Do you want to install Lazy Weather? (Y/n) " -n
if [[ $REPLY =~ ^[Nn]$ ]]; then
    echo "Lazy Weather installation skipped."
    exit 0
fi

curl -sSL https://raw.githubusercontent.com/apapamarkou/lazy-weather/main/install | bash

echo "✅ Lazy Weather installed!"
sleep 2